USE [Tools]
GO

/****** Object:  Table [dbo].[FileWatcherConfig]    Script Date: 6/29/2016 1:54:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FileWatcherConfig](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Folder] [varchar](255) NULL,
	[StoredProc] [varchar](255) NULL,
	[Notify] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


